### ISSUE TITLE
Allow Redownload of Backup as JSON or .tachibk

### ISSUE THREAD

**Issue by Animeboynz** [Animeboynz/Mihon-Backup-Viewer#10]

**Comment by BrutuZ** [comment]
#11 must be sorted out first to avoid data loss from dropping fields exclusive to forks' schemas

**Comment by Animeboynz** [comment]
I created a demo to attempt re-encoding, I want to say it worked but I noticed that the ID for the source had changed somewhere along the way. It was all consistent but different to the original. I'll need to investigate it further.

**Comment by Animeboynz** [comment]
Opinions?
![image](https://github.com/Animeboynz/Mihon-Backup-Viewer/assets/40583749/796b3c70-2293-48d7-b44d-ef930e935ae9)

**Comment by Animeboynz** [comment]
Completed with #44

**Comment by BrutuZ** [comment]
I suspect the tachibk won't be fully compatible, the app settings are not getting decoded properly and will likely get maimed on encode.
I couldn't figure out a way to declare that in the schema yet.
![image](https://github.com/Animeboynz/Mihon-Backup-Viewer/assets/7104931/b34a3515-ac6e-429d-8c82-94154dc759f0)
