### ISSUE TITLE
Get schema.proto from Mihon's Repo

### ISSUE THREAD

**Issue by Animeboynz** [Animeboynz/Mihon-Backup-Viewer#11]
It is currently static and will need to be manually updated if it changes in the future.
I guess we can also add a selector to support multiple forks.

**Comment by Animeboynz** [comment]
I dont even know if the schema changes over time or between forks, but this is just a reminder for me to check them out.

**Comment by BrutuZ** [comment]
Yes for both. My script fetches it

**Comment by Animeboynz** [comment]
Yeah I noticed, that's the only reason I added this here. You really made that python program futureproof, even having multiple repo options.

**Comment by NGB-Was-Taken** [comment]
This should probably be a scheduled job instead of getting fetching from github and compiling every time the user asks for it.

**Comment by BrutuZ** [comment]
What the... I could swear I'd sent this exact comment earlier today xD
I even added a [dump command to my script](https://github.com/BrutuZ/tachibk-converter/commit/0c12e80c82b1fe7f70764c675f91f4ad1a072b86) because of it

**Comment by Animeboynz** [comment]
> Yes for both. My script fetches it

Okay so if the schema changes over time what would happen if someone wanted to try decode an older backup?
or are the changes to the schema backwards compatible?

**Comment by BrutuZ** [comment]
Their backups are backwards compatible and even cross-fork. They only add new fields to the schema, and any fields in the backup not in the schema (like cross-forks) are just dropped

**Comment by Animeboynz** [comment]
I've turned this into a GitHub Workflow which we can trigger from the Actions tab and it will automatically fetch and commit the new schema.

Marking this as closed now.
