### ISSUE TITLE
Remember Settings

### ISSUE THREAD

**Issue by BrutuZ** [Animeboynz/Mihon-Backup-Viewer#36]
Would be nice to remember the settings when we have them (#30 Soon™) so that we don't need to navigate menus on every refresh.
Need to decide on either Cookies or Local Storage.

If the latter, maybe even remember the last used JSON and skip the file selection screen? Could add a button to call it in the settings dialog to change the loaded backup data.

**Comment by Animeboynz** [comment]
Remembering last used settings sounds cool but I don't think I'm a fan of storing the last used JSON. 
1. Imagine a large backup stored in Local Storage, which people might not realise needs to be manually deleted
2. It could be a privacy issue. What if someone uses the tool closes the website and someone using the computer after them checks history or goes to the same site, it auto loads the last loaded backup.
3. It would mean that users have to manually go into settings and choose an option to fully close their backup.

**Comment by BrutuZ** [comment]
I wasn't sure about that one either, that's why it ended up in a separate paragraph. It was more of an afterthought out of a pet peeve I got from redoing that first step on every refresh to test a change xD

**Comment by Animeboynz** [comment]
I made it so that Sort order is saved to local storage as that is a personal option people might not want to select every time. 
As of now I chose not to store filtering as it might confuse people why entries are not showing up.
