### ISSUE TITLE
Sort Library as Alphabetical

### ISSUE THREAD

**Issue by Animeboynz** [Animeboynz/Mihon-Backup-Viewer#4]
As this is the default order on Mihon.

**Comment by BrutuZ** [comment]
Is it? I've switched it to date instead on my copy, made more sense :P

**Comment by Animeboynz** [comment]
That fair my library is really spread out across categories so I left it as Alphabetical. We could do last update but I really don't want to figure that out.

**Comment by BrutuZ** [comment]
Last Update is easy since there's the `lastModifiedAt` field with it. There's also `favoriteModifiedAt`
Last Read is the tricky one since we'd have to parse from chapters history, especially given how common it is to have backlogged entries with no history at all.

**Comment by Animeboynz** [comment]
Oh I forgot about `lastModifiedAt`

**Comment by Animeboynz** [comment]
Completed with #30
