### ISSUE TITLE
`SourceId` being rounded during Protobuf conversion.

### ISSUE THREAD

**Issue by Animeboynz** [Animeboynz/Mihon-Backup-Viewer#43]
Using python protobuf converter.
![image](https://github.com/Animeboynz/Mihon-Backup-Viewer/assets/40583749/a2988303-0ca3-47e4-a4d7-aaf15b195d99)
Using the website protobuf converter.
![image](https://github.com/Animeboynz/Mihon-Backup-Viewer/assets/40583749/2b2cacb8-5610-4a25-8afb-2252eeaf1d92)

**Comment by BrutuZ** [comment]
Cannot repro
![image](https://cdn.discordapp.com/attachments/986447226844885062/1254200623201517679/image.png?ex=6678a0da&is=66774f5a&hm=462d6dee8fa14ba439238381ab78aa05dea177392cf8c206cd9d324c7a080b3f&)
