### ISSUE TITLE
Display tracking status

### ISSUE THREAD

**Issue by NGB-Was-Taken** [Animeboynz/Mihon-Backup-Viewer#48]
I don't just mean displaying "tracked" and "untracked". I mean displaying every tracking information we have from `tracking` field. 

I want opinions on how it should be displayed while I implement getting the data itself.

**Comment by BrutuZ** [comment]
Tiny favicons with links to their respective tracker page on the details page

**Comment by NGB-Was-Taken** [comment]
So you mean stuff like tracker status, score, start date, last read chapter, reading start/end date shouldn't be displayed?

**Comment by BrutuZ** [comment]
I don't really see it serving any purpose. One click on your favorite tracker icon and all the info is there, editable too.

**Comment by NGB-Was-Taken** [comment]
Well, it is a "backup viewer". Why not display info that is in backup?

**Comment by BrutuZ** [comment]
Because it's just a cache of your own information on third-parties ¯\\\_(ツ)_/¯

Tell you what, put the score and dates on the icon's hover, then it's there but doesn't clutter
