### ISSUE TITLE
Implement Kebab Menu on `mangaItems`

### ISSUE THREAD

**Issue by Animeboynz** [Animeboynz/Mihon-Backup-Viewer#53]
Initially have at least 2 options

1. Edit
2. Delete

**Comment by Animeboynz** [comment]
```
```

**Comment by Animeboynz** [comment]
```js
{
  "backupManga": [
    {
      "source": "1024627298672457456", //Pointless to Change
      "url": "https://chapmanganato.com/manga-ay956581", //Pointless to Change
      "title": "Wagatsuma-San Wa Ore No Yome", //Pointless to Change
      "author": "Kuraishi Yuu", //Pointless to Change
      "description": "Aoshima Hitoshi is a second year student in high school, who wishes he had a girlfriend.", //Pointless to Change
      "genre": [ "Comedy", "Romance" ], //Pointless to Change
      "status": 2, //Pointless to Change
      "thumbnailUrl": "https://avt.mkklcdnv6temp.com/20/f/4-1583470500.jpg", //Pointless to Change
      "dateAdded": "1603065046895", //Editable
      "chapters": [
        {
          "url": "https://chapmanganato.to/manga-ay956581/chapter-1", //Pointless to Change
          "name": "Chapter 1", //Pointless to Change
          "scanlator": "chapmanganato.to", //Pointless to Change
          "read": true, //Editable but pointless
          "dateFetch": "1625024557414", //Pointless to Change
          "dateUpload": "1566648000000", //Pointless to Change
          "chapterNumber": 1, //Pointless to Change
          "sourceOrder": "95" //Pointless to Change
        }
      ],
      "categories": [ "6" ], //Editable
      "tracking": [
        {
          "syncId": 1, //Pointless to Change
          "libraryId": "0", //????????
          "trackingUrl": "https://myanimelist.net/manga/48035", //Editable
          "title": "Wagatsuma-san wa Ore no Yome", //Editable
          "lastChapterRead": 111, //Editable but pointless
          "totalChapters": 111, //Pointless to Change
          "status": 2, //????????
          "mediaId": "48035" //MAL ID - Editable
        }
      ],
      "viewerFlags": 0, //????????
      "history": [
        {
          "url": "/chapter/f03bfdcd-aeae-459d-9469-3ea9c6913ea0", //Pointless to Change
          "lastRead": "1675498612159", //Editable
          "readDuration": "2042" //Editable
        }
      ],
      "lastModifiedAt": "1717542954", //Editable
      "favoriteModifiedAt": "1717542954" //Editable
    }
  ],

  "backupCategories": [
    {
      "name": "Reading", //Editable but pointless
      "order": "1", //Editable but pointless
      "flags": "64" //????????
    }
  ]
}
```

**Comment by BrutuZ** [comment]
Fun fact, the one time I edited my backup file was precisely do switch source IDs 😂

`...ModifiedAt` fields seem pointless to edit.
`tracking` fields would need some extra work. Would've nice in the recent AniList searchpocalypse
`chapter.read` seems relevant enough, although a lot easier and more intuitive to do in the app.
And let's not forget the forks `custom...` fields for title, thumbnail, description, genres, etc...

**Comment by Animeboynz** [comment]
> Fun fact, the one time I edited my backup file was precisely do switch source IDs 😂

Does that not break it. cus all the chapter urls would be for the old source?

> `chapter.read` seems relevant enough, although a lot easier and more intuitive to do in the app. 

yeah thats why I put it as pointless xD `"read": true, //Editable but pointless`

> And let's not forget the forks `custom...` fields for title, thumbnail, description, genres, etc...

Tru

**Comment by BrutuZ** [comment]
> Does that not break it. cus all the chapter urls would be for the old source?

Not in that instance because it was the same source handled by a different extension, it was the most efficient way of mass migrating.
Veeery niche case, just thought it was fun to bring it up.

**Comment by Animeboynz** [comment]
> Veeery niche case, just thought it was fun to bring it up.

I've actually had the same issue. I wish I was smart enough to do that back then. I had to manually migrate ~350 entries.

**Comment by NGB-Was-Taken** [comment]
In the `tracking` field, `libraryId` should be pointless to change (and actually can break tracking in some trackers). `status` may also be pointless to change (status is stuff like reading, completed, on hold, dropped)

**Comment by Animeboynz** [comment]
I see, lemme edit it.

**Comment by NGB-Was-Taken** [comment]
Looks like `flags` in `backupCategories` are for sorting so should be editable, maybe even via a GUI?
Check this file for more information https://github.com/mihonapp/mihon/blob/main/domain/src/main/java/tachiyomi/domain/library/model/LibrarySortMode.kt

**Comment by BrutuZ** [comment]
Sounds about right, seems like a bitwise list that had some values dropped at some point https://github.com/mihonapp/mihon/blob/master/domain/src/main/java/tachiyomi/domain/library/model/LibrarySortMode.kt#L25-L49

**Comment by NGB-Was-Taken** [comment]
> Sounds about right, seems like a bitwise list that had some values dropped at some point https://github.com/mihonapp/mihon/blob/master/domain/src/main/java/tachiyomi/domain/library/model/LibrarySortMode.kt#L25-L49

Quoting AntsyLich on this:
> just to make sure, flags are sorting options, right?
>> And display mode but that isn't used anymore

**Comment by Animeboynz** [comment]
I'll be fair I have no idea how to implement the kebab menu. 😭
