### ISSUE TITLE
Mimic app's sorting modes

### ISSUE THREAD

**Issue by BrutuZ** [Animeboynz/Mihon-Backup-Viewer#66]
[Mihon](https://github.com/mihonapp/mihon/blob/9e2f97eeb8a0f1d1b353dc3e77fb64d69b568674/app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt#L279-L316) or [SY's](https://github.com/jobobby04/TachiyomiSY/blob/master/app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt#L412-L458) logic into
https://github.com/Animeboynz/Mihon-Backup-Viewer/blob/cf89997098c75bd311bfcad39bd0be6f34dae556/scripts/library.js#L89-L106

**Comment by Animeboynz** [comment]
Is this basically just adding a all the sort options available in the app?
![Screenshot_20240629_135201_Mihon](https://github.com/Animeboynz/Mihon-Backup-Viewer/assets/40583749/a04b2bee-6a43-4dba-9d6f-b403982a957b)

**Comment by BrutuZ** [comment]
Pretty much. I see it as a long-ish term goal, current ones work well enough for now so the issue is mostly to keep it in mind for future improvements when feeling bored

**Comment by Animeboynz** [comment]
Fair fair. Makes sense
