### ISSUE TITLE
Fix time conversion inconsistency

### ISSUE THREAD

**Issue by BrutuZ** [Animeboynz/Mihon-Backup-Viewer#91]
Chapter read times are correct, the ones in the Edit modal for manga entries are all converted to UTC, should use the user locale instead.

**Comment by Animeboynz** [comment]
Oh just remembered I only added it as a comment not an issue 🤣
https://github.com/Animeboynz/Mihon-Backup-Viewer/pull/77#issuecomment-2226777491
