### ISSUE TITLE
Title justification

### ISSUE THREAD

**Issue by BrutuZ** [Animeboynz/Mihon-Backup-Viewer#97]
Hyphenation might be tricky with romaji, but left-alignment will probably look better than this weird odd spacing (there are worse examples) 
![Screenshot_20240724-042358](https://github.com/user-attachments/assets/3f2a480f-5453-419f-b000-ec8ea12724ff)

**Comment by Animeboynz** [comment]
Yeah there are some in my library which look so bad. Would definately call this a high priority.
